#!/usr/bin/env python3
"""Node that broadcasts a CSV as a tf."""

import argparse
import json
import pathlib
import sys

import geometry_msgs.msg
import rclpy
import rclpy.node
import rclpy.utilities
import tf2_ros

DEFAULT_ORDER = ["x", "y", "z", "qw", "qx", "qy", "qz"]


def _parse_file(
    trajectory_file, parent, child, skip_first=True, order=None, origin=None
):
    if order is None:
        order = DEFAULT_ORDER
    else:
        order = json.loads(order)

    if origin:
        origin = json.loads(origin)
    else:
        origin = [0.0, 0.0, 0.0]

    transforms = []
    have_first_line = False
    with open(trajectory_file, "r") as fin:
        for line in fin:
            if not have_first_line:
                have_first_line = True
                if skip_first:
                    continue

            values = [x.strip() for x in line.split(",")]
            time_ns = int(values[0])
            pose = {n: float(x) for n, x in zip(order, values[1:])}

            t = geometry_msgs.msg.TransformStamped()
            t.header.stamp = rclpy.time.Time(nanoseconds=time_ns).to_msg()
            t.header.frame_id = parent
            t.child_frame_id = child
            t.transform.translation.x = pose["x"] - origin[0]
            t.transform.translation.y = pose["y"] - origin[1]
            t.transform.translation.z = pose["z"] - origin[2]
            t.transform.rotation.w = pose["qw"]
            t.transform.rotation.x = pose["qx"]
            t.transform.rotation.y = pose["qy"]
            t.transform.rotation.z = pose["qz"]
            transforms.append(t)

    return transforms


class CsvToTfNode(rclpy.node.Node):
    """Node that uses a CSV to simulate a live TF."""

    def __init__(
        self, transforms, offset=0.0, lookahead=0.0, stale=0.5, poll_period=0.01
    ):
        """Initialize the node."""
        super().__init__("csv_to_tf")
        self._idx = 0
        self._transforms = transforms
        self._broadcaster = tf2_ros.TransformBroadcaster(self)

        self._offset = rclpy.duration.Duration(seconds=offset)
        self._stale_threshold = rclpy.duration.Duration(seconds=stale)
        self._lookahead = rclpy.duration.Duration(seconds=lookahead)
        self.get_logger().info(
            f"offset: {self._offset}, lookahead: {self._lookahead}, stale: {self._stale_threshold}"
        )

        self._timer = self.create_timer(poll_period, self._callback)

    def _curr_tf_is_stale(self, ros_stamp):
        # we want to reject any transforms that are more than stale_threshold_s than the current stamp
        curr_stamp = self._get_curr_tf_stamp()
        if curr_stamp is None:
            return False

        return ros_stamp - curr_stamp > self._stale_threshold

    def _get_curr_tf_stamp(self):
        if self._idx >= len(self._transforms):
            return None

        stamp = rclpy.time.Time.from_msg(self._transforms[self._idx].header.stamp)
        return stamp + self._offset

    def _callback(self):
        stamp = self.get_clock().now()

        prev_idx = self._idx
        while self._curr_tf_is_stale(stamp):
            self._idx += 1

        num_dropped = self._idx - prev_idx
        if num_dropped > 0:
            self.get_logger().warn(
                f"Dropped {num_dropped} TFs older than {stamp.nanoseconds} [ns]"
            )

        if self._idx >= len(self._transforms):
            self.get_logger().info("Finished publishing transforms")
            self._timer.cancel()
            return

        next_stamp = self._get_curr_tf_stamp()
        diff_str = f"diff: {(next_stamp - stamp).nanoseconds} [ns]"
        self.get_logger().debug(
            f"waiting for time {next_stamp.nanoseconds} [ns] ({diff_str})"
        )
        # if the next TF timestamp is ahead of the current ROS time by more than the lookahead,
        # don't publish anything
        if next_stamp - stamp > self._lookahead:
            return

        self.get_logger().debug(f"sending {next_stamp.nanoseconds} [ns]")
        msg = self._transforms[self._idx]
        msg.header.stamp = next_stamp.to_msg()  # reset header stamp
        self._broadcaster.sendTransform(msg)
        self._idx += 1


def main(args=None):
    """Do stuff."""
    parser = argparse.ArgumentParser(
        "Node that publishes parent_T_child from a CSV file"
    )
    parser.add_argument("filepath")
    parser.add_argument(
        "--offset", default=0.0, help="Amount of time to offset stamps by"
    )
    parser.add_argument(
        "--lookahead", default=0.0, help="Amount of lead time to publish TF by"
    )
    parser.add_argument(
        "--stale", default=0.5, help="Amount of time before a TF is stale"
    )
    parser.add_argument(
        "--poll_period", default=0.01, help="Amount of time before a TF is stale"
    )
    parser.add_argument("--parent", default="odom", help="frame ID for parent frame")
    parser.add_argument("--child", default="base_link", help="frame ID for child frame")
    parser.add_argument(
        "--origin", default=None, help="origin coordinates to use in json"
    )
    parser.add_argument("--column_order", default=None, help="column names in json")
    parser.add_argument(
        "--parse_first", action="store_true", help="parse first CSV line"
    )
    args, rest = parser.parse_known_args()

    filepath = pathlib.Path(args.filepath).expanduser().absolute()
    if not filepath.exists():
        sys.exit(f"Trajectory file {filepath} does not exist!")

    transforms = _parse_file(
        filepath,
        args.parent,
        args.child,
        origin=args.origin,
        order=args.column_order,
        skip_first=not args.parse_first,
    )

    rclpy.init(args=rest)
    try:
        node = CsvToTfNode(
            transforms,
            offset=args.offset,
            lookahead=args.lookahead,
            stale=args.stale,
            poll_period=args.poll_period,
        )
        node.get_logger().info(f"Publishing {args.parent}_T_{args.child}")
        rclpy.spin(node)
        node.destroy_node()
    except KeyboardInterrupt:
        pass
    finally:
        rclpy.try_shutdown()


if __name__ == "__main__":
    main()
