#!/usr/bin/env python3

import numpy as np
import rclpy
import tf2_ros
from geometry_msgs.msg import TransformStamped, Pose
from nav_msgs.msg import Odometry
from rclpy.node import Node
from scipy.spatial.transform import Rotation


def _invert_pose(p):
    p_inv = np.zeros((4, 4))
    p_inv[:3, :3] = p[:3, :3].T
    p_inv[:3, 3] = -p[:3, :3].T @ p[:3, 3]
    p_inv[3, 3] = 1.0
    return p_inv


def _rot_from_pose(pose):
    q = [pose.orientation.x, pose.orientation.y, pose.orientation.z, pose.orientation.w]
    return Rotation.from_quat(q).as_matrix()


def _mat_from_pose(pose):
    pose_out = np.zeros((4, 4))
    pose_out[:3, :3] = _rot_from_pose(pose)
    pose_out[:3, 3] = [pose.position.x, pose.position.y, pose.position.z]
    pose_out[3, 3] = 1.0
    return pose_out


def _pose_from_mat(p):
    q = Rotation.from_matrix(p[:3, :3]).as_quat()

    msg = Pose()
    msg.position.x = p[0, 3]
    msg.position.y = p[1, 3]
    msg.position.z = p[2, 3]
    msg.orientation.x = q[0]
    msg.orientation.y = q[1]
    msg.orientation.z = q[2]
    msg.orientation.w = q[3]
    return msg


def _exp(rho, theta):
    theta_norm = np.linalg.norm(theta)
    xi_hat = np.zeros((4, 4))
    theta_hat = np.array(
        [[0, -theta[2], theta[1]], [theta[2], 0, -theta[0]], [-theta[1], theta[0], 0]]
    )
    xi_hat[:3, :3] = theta_hat
    xi_hat[:3, 3] = rho
    return (
        np.eye(4)
        + xi_hat
        + (1 - np.cos(theta_norm)) / (theta_norm**2) * xi_hat @ xi_hat
        + (theta_norm - np.sin(theta_norm)) / (theta_norm**3) * xi_hat @ xi_hat @ xi_hat
    )


def _calc_odom_delta(odom_old, odom_new):
    w_T_old = _mat_from_pose(odom_old.pose.pose)
    w_T_new = _mat_from_pose(odom_new.pose.pose)
    delta = _invert_pose(w_T_old) @ w_T_new
    return delta


class NoisyTransformPublisher(Node):
    """Node that republishes TFs with noise added."""

    def _get_param(self, name, default=None):
        return self.declare_parameter(name, default).get_parameter_value()

    def __init__(self):
        super().__init__("noisy_tf_publisher_node")
        self._last_noisy_odom = None
        self._poses = []

        self._parent_frame = self._get_param("parent_frame", "odom").string_value
        self._child_frame = self._get_param("child_frame", "base_link").string_value
        self._yaw_std_dev = self._get_param("yaw_std_dev", 0.001).double_value
        self._xy_std_dev = self._get_param("xy_std_dev", 0.001).double_value
        self._z_std_dev = self._get_param("z_std_dev", 0.001).double_value

        self._start_from_origin = self._get_param("start_from_origin", True).bool_value
        self._add_noise = self._get_param("add_noise", True).bool_value
        self._wrong_velocity_frame = self._get_param(
            "wrong_velocity_frame", False
        ).bool_value

        seed = self._get_param("random_seed", 0).integer_value
        self._rng = np.random.default_rng(seed=seed if seed > 0 else None)

        self._br = tf2_ros.TransformBroadcaster(self)
        self._sub = self.create_subscription(Odometry, "odom", self._odom_cb, 10)
        self._pub = self.create_publisher(Odometry, "~/noisy_odom", 10)

    def _odom_cb(self, msg):
        self._poses.append(_mat_from_pose(msg.pose.pose))
        if len(self._poses) == 1:
            self._last_noisy_odom = Odometry() if self._start_from_origin else msg
            return

        map_T_new = self._poses[-1]
        map_T_old = self._poses[-2]
        old_T_new = _invert_pose(map_T_old) @ map_T_new
        if self._add_noise:
            old_T_new @= _exp(*self._sample_noise)

        self._last_noisy_odom = self._add_odom_noise(self._last_noisy_odom, msg, old_T_new)

        self._publish_noisy_transform(msg.header.stamp, self._last_noisy_odom.pose.pose)
        self._pub.publish(self._last_noisy_odom)

    def _publish_noisy_transform(self, time, noisy_pose):
        msg = TransformStamped()
        msg.header.stamp = time
        msg.header.frame_id = self._parent_frame
        msg.child_frame_id = self._child_frame
        msg.transform.translation.x = noisy_pose.position.x
        msg.transform.translation.y = noisy_pose.position.y
        msg.transform.translation.z = noisy_pose.position.z
        msg.transform.rotation = noisy_pose.orientation
        self._br.sendTransform(msg)

    def _sample_noise(self):
        t_noise = np.zeros(3)
        t_noise[:2] = self._rng.normal(scale=self._xy_std_dev)
        if self._z_std_dev > 0.0:
            t_noise[2] = self._rng.normal(scale=self._z_std_dev)

        R_noise = [0, 0, self._rng.normal(scale=self._yaw_std_dev)]
        return t_noise, R_noise

    def _add_odom_noise(self, prev_noisy_odom, cur_gt_odom, pose_delta):
        prev_pose = _mat_from_pose(prev_noisy_odom.pose.pose)
        updated_pose = prev_pose @ pose_delta
        if self._add_noise:
            t_noise, R_noise = self._sample_noise()
            updated_pose @= _exp(t_noise, R_noise)

        curr_twist = cur_gt_odom.twist.twist
        vel = np.array([curr_twist.linear.x, curr_twist.linear.y, curr_twist.linear.z])
        if self._wrong_velocity_frame:
            R_gt = _rot_from_pose(cur_gt_odom.pose.pose)
            R_noisy = updated_pose[:3, :3]
            vel = (R_noisy.T @ R_gt) @ vel

        updated_odom = Odometry()
        updated_odom.header = cur_gt_odom.header
        updated_odom.pose.pose = _pose_from_mat(updated_pose)
        updated_odom.twist.twist.linear.x = vel[0]
        updated_odom.twist.twist.linear.y = vel[1]
        updated_odom.twist.twist.linear.z = vel[2]
        return updated_odom


def main(args=None):
    rclpy.init()
    try:
        node = NoisyTransformPublisher()
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        rclpy.try_shutdown()


if __name__ == "__main__":
    main()
