---
sinks:
  - type: ReconstructionVisualizer
    max_weight: 1000.0
    slice_height: 0.0
    point_size: 0.01
    mesh_coloring:
      type: UniformMeshColoring
      color: [255, 0, 0]
  - type: TsdfOccupancyPublisher
    extraction:
      min_distance: 0.25
