---
input:
  type: RosInput
  tf_verbosity: 1
  clear_queue_on_fail: true
  inputs:
    lidar_sensor:
      receiver:
        type: PointcloudReceiver
      sensor:
        type: lidar
        min_range: $(arg sensor_min_range)
        max_range: $(arg sensor_max_range)
        is_asymmetric: false
        horizontal_resolution: 0.2 # true resolution: 360 / 1800 = 0.2
        vertical_resolution: 2.0   # true resolution: 30 / 16 = 2.0
        horizontal_fov: 360.0
        vertical_fov: 30.0
        vertical_fov_top: 15.0
        extrinsics:
          type: ros
          sensor_frame: "$(arg sensor_frame)"
