---
semantic_colormap_file: $(find hydra_ros)/config/color/ade20k_indoor.csv
semantic_label_remap_filepath: ''
enable_frontend_output: true
exit_after_clock: false
frontend:
  type: FrontendModule
  enable_places: true
  use_2d_places: true
  objects:
    bounding_box_type: AABB
  pose_graph_tracker:
    type: PoseGraphFromOdom
backend:
  type: BackendModule
  pgmo:
    add_initial_prior: true
  dsg:
    optimize_on_lc: true
    use_zmq_interface: true
    zmq_recv_url: tcp://127.0.0.1:8002
    zmq_send_url: tcp://127.0.0.1:8001
    zmq_send_mesh: true
reconstruction:
  type: ReconstructionModule
enable_lcd: false
lcd_use_bow_vectors: true
lcd:
  gnn_lcd:
    label_embeddings_file: ''
    object_model_path: $(find hydra)/models/lcd/object_gnn.onnx
    places_model_path: $(find hydra)/models/lcd/place_gnn.onnx
  use_gnn_descriptors: false
log_path: $(find hydra)/output/lis_spot
log_timing_incrementally: false
use_sim_time: true
