---
input:
  type: RosInput
  inputs:
    - receiver:
        type: PointcloudReceiver
      sensor:
        type: camera_info
        min_range: $(arg sensor_min_range)
        max_range: $(arg sensor_max_range)
        camera_info_topic: $(arg rgb_info_topic)
        extrinsics:
          type: kimera
          sensor_frame: $(arg sensor_frame)
          sensor_filepath: $(arg kimera_sensor_filepath)
