---
input:
  type: lidar
  min_range: 0.1
  max_range: 10.0
  is_asymmetric: false
  vertical_fov: 60.0
  horizontal_fov: 360.0
  horizontal_resolution: 1.4
  vertical_resolution: .2
  extrinsics:
    type: ros
