---
_tracker_config: &tracker_config
  type: MaxIouTracker
  track_by: voxels
  min_semantic_iou: 0.1
  min_cross_iou: 0.3
  voxel_size: 0.2
  temporal_window: 5.0
  min_num_observations: 10
_lidar_integrator_config: &lidar_integrator
  use_constant_weight: true
  extra_integration_distance: 3.0
  extra_integration_distance_labels: [4, 5, 6, 7, 8, 9, 10, 20, 22, 30]
  interpolation_method: {max_depth_difference_m: 0.9}
  semantic_integrator: {type: SingleLabelIntegrator, labels_to_ignore: [-1]}
paths: [khronos, khronos_ros]
active_window:
  type: ActiveWindow
  sensor_map_mode: Strict
  sensors:
    rgbd:
      object_detector: {type: ConnectedSemantics, min_cluster_size: 30, grid_size: 0.2, max_range: 7.0}
      tracker: *tracker_config
      projective_integrator: {semantic_integrator: {type: SingleLabelIntegrator}}
    velodyne16:
      object_detector: {type: ConnectedSemantics, min_cluster_size: 30, grid_size: 0.2, max_range: 15.0}
      tracker: *tracker_config
      projective_integrator: *lidar_integrator
    ouster64:
      object_detector: {type: ConnectedSemantics, min_cluster_size: 30, grid_size: 0.2, max_range: 15.0}
      tracker: *tracker_config
      projective_integrator: *lidar_integrator
  object_extractor:
    type: MeshObjectExtractor
    min_object_allocation_confidence: 0.5
    min_object_volume: 0.005  # m^3
    max_object_volume: 100.0  # m^3
    only_extract_reconstructed_objects: true
    min_object_reconstruction_confidence: 0.0
    min_object_reconstruction_observations: 10
    object_reconstruction_resolution: -0.1  # Positive: voxel size in meters.
    visualize_classification: false
    # object_reconstruction_resolution: 0.05
    # visualize_classification: true
    projective_integrator:
      sensor_map_mode: Strict
      sensors:
        rgbd: {}
        velodyne16: {use_constant_weight: true}
        ouster64: {use_constant_weight: true}
  khronos_sinks:
    - type: ActiveWindowVisualizer
      sensor_displays:
        sensor_map_mode: Strict
        sensors:
          rgbd: {}
          velodyne16: {height_scale: 32.0}
          ouster64: {height_scale: 8.0}
frontend:
  enable_mesh_objects: false
