---
semantic_colormap_file: $(arg semantic_map_path)
semantic_label_remap_filepath: $(arg semantic_label_remap_filepath)
exit_after_clock: $(arg exit_after_clock)
log_path: $(arg log_path)
log_timing_incrementally: $(arg log_timing_incrementally)
enable_frontend_output: $(arg enable_frontend_output)
frontend:
  type: FrontendModule
  enable_places: $(arg enable_places)
  objects:
    bounding_box_type: $(arg bounding_box_type)
  pose_graph_tracker:
    type: $(arg pose_graph_tracker_type)
backend:
  type: BackendModule
  pgmo:
    add_initial_prior: $(arg add_initial_prior)
  dsg:
    optimize_on_lc: $(arg optimize_on_lc)
    use_zmq_interface: $(arg use_zmq_interface)
    zmq_send_url: $(arg zmq_send_url)
    zmq_recv_url: $(arg zmq_recv_url)
    zmq_send_mesh: $(arg zmq_send_mesh)
reconstruction:
  type: ReconstructionModule
enable_lcd: $(arg enable_dsg_lcd)
lcd_use_bow_vectors: $(arg lcd_use_bow_vectors)
lcd:
  use_gnn_descriptors: $(arg use_gnn_descriptors)
  gnn_lcd:
    object_model_path: $(arg lcd_gnn_object_model)
    places_model_path: $(arg lcd_gnn_places_model)
    label_embeddings_file: $(arg lcd_gnn_label_embeddings)
